apiVersion: v1
kind: ServiceAccount
metadata:
  name: veba-ui
  namespace: vmware-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: veba-ui
  namespace: vmware-functions
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["watch", "get", "list", "create", "update", "delete"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["watch", "get", "list", "create", "update", "delete"]
  - apiGroups: ["eventing.knative.dev"]
    resources: ["triggers"]
    verbs: ["watch", get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: veba-ui
  namespace: vmware-functions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: veba-ui
subjects:
- kind: ServiceAccount
  name: veba-ui
  namespace: vmware-system